apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-services
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dawood9598/gitops-infrastructure.git
    targetRevision: HEAD
    path: infra/kubernetes/argocd/applications/backend-api
  destination:
    server: https://kubernetes.default.svc
    namespace: tekton-pipelines